### ISSUE TITLE
`SELECT SPLIT` buttons are triggered on screens without split selection

### ISSUE THREAD

**Issue by Erudition** [Erudition/linnstrument-firmware#5]
On screens like OCTAVE/TRANSPOSE and VOLUME, the top row (7) is disabled and the current split(s) is highlighted (LEFT/RIGHT) on pads 15 and 16. Tapping these switches leads to a change in split, changing the screen to the split's color theme, but remaining on the screen.

In the GUITAR TUNING editor screen (GLOBAL SETTINGS -> long press r3c6 (ROW OFFSET group, GUITAR label)), there is no such split selection highlighted and the top row is enabled for sliding adjustment. However, tapping LEFT or RIGHT on this screen still toggles the color theme between the two splits. The GUITAR TUNING editor applies to both splits, so this does not make sense.

Worse, if an adjustment is made to the guitar tuning first, tapping LEFT or RIGHT will kick you to the PER-SPLIT SETTINGS screen.

Worse still, if you pass over either of these pads during an adjustment it will switch splits, and on the second time (or if it's not your first adjustment, it will abruptly cancel the slide and again kick you to the PER-SPLIT SETTINGS screen.

This issue is inherited from the stock firmware, all Linnstruments have it.

**Comment by Erudition** [comment]
Blind fix attempted in https://github.com/Erudition/linnstrument-firmware/commit/917b434bf8297ecb4821141e149130dbafb6e8b9

**Comment by TallKite** [comment]
Erudition's fix worked
